### ISSUE TITLE
Troubleshooting section/page

### ISSUE THREAD

**Issue by kevmodrome** [sveltech/routify-site-2020#121]
Would be neat with a page dedicated to troubleshooting. Sometimes errors are hard. Copying what I wrote on discord, it should be descriptive enough:

> I'm going to go ahead and claim that there is a good reason to add a Troubleshooting section to the website.
I've run into an issue a couple of times (and now a work buddy ran into the same issue) where we get errors like `Route coule not be found. Make sure ... or ... exists. A restart may be required.`.
The solution is usually to edit some kind of link, like: `href="my-link"` to `href="/my-link"` or the like.
Sometimes I've noticed it happening to svgs and stuff as well, so you get /video-camera.svg.svelte which is a bit strange :stuck_out_tongue:

**Comment by Wolfr** [comment]
I thought about how we could add a section like this:

> ## Common issues
> 
> This section is listing some issues that you might have during development.
> 
> ```Route could not be found. Make sure ... or ... exists. A restart may be required.```
> 
>  The solution is usually to edit some kind of link, like: href="my-link" to href="/my-link" or the like.

But to be honest, that solution sounds a bit vague. Like: go through all your links and do what?

It also sounds like Routify should catch that problem as a framework instead of providing this kind of section.

If more of these “vague” issues pop up we can surely document them. But for now I wouldn't add this to the site as not to make it more difficult to maintain than it needs to be.

**Comment by jakobrosenberg** [comment]
**Electron apps need local tmp dir** ``routify --routify-dir routify``

---

**Comment by Wolfr** [comment]
I guess we could add `--routify-dir` to the CLI options then on this page?

https://routify.dev/docs/config/basics

Possible description: The path where Routify keeps its temporary files

Is this correct?

**Comment by jakobrosenberg** [comment]
That sounds correct. Maybe replace keeps with creates or generates.

**Comment by Wolfr** [comment]
I think we could add common issues to the FAQ now.
https://routify.dev/guide/faq

Closing this one due to stale/old conversation.
